package io.lowcode.platform.domain;

import static io.lowcode.platform.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class DocumentMetadataVersionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentMetadataVersionAllPropertiesEquals(DocumentMetadataVersion expected, DocumentMetadataVersion actual) {
        assertDocumentMetadataVersionAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentMetadataVersionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentMetadataVersionAllUpdatablePropertiesEquals(
        DocumentMetadataVersion expected,
        DocumentMetadataVersion actual
    ) {
        assertDocumentMetadataVersionUpdatableFieldsEquals(expected, actual);
        assertDocumentMetadataVersionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentMetadataVersionAutoGeneratedPropertiesEquals(
        DocumentMetadataVersion expected,
        DocumentMetadataVersion actual
    ) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentMetadataVersionUpdatableFieldsEquals(
        DocumentMetadataVersion expected,
        DocumentMetadataVersion actual
    ) {
        assertThat(actual)
            .as("Verify DocumentMetadataVersion relevant properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a ->
                assertThat(a.getDocumentMetadataVersionName())
                    .as("check documentMetadataVersionName")
                    .isEqualTo(expected.getDocumentMetadataVersionName())
            )
            .satisfies(a ->
                assertThat(a.getDocumentMetadataVersionCode())
                    .as("check documentMetadataVersionCode")
                    .isEqualTo(expected.getDocumentMetadataVersionCode())
            )
            .satisfies(a -> assertThat(a.getFlagActive()).as("check flagActive").isEqualTo(expected.getFlagActive()))
            .satisfies(a -> assertThat(a.getCreateUser()).as("check createUser").isEqualTo(expected.getCreateUser()))
            .satisfies(a ->
                assertThat(a.getCreatedAt())
                    .as("check createdAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreatedAt())
            )
            .satisfies(a -> assertThat(a.getUpdateUser()).as("check updateUser").isEqualTo(expected.getUpdateUser()))
            .satisfies(a ->
                assertThat(a.getUpdatedAt())
                    .as("check updatedAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getUpdatedAt())
            )
            .satisfies(a -> assertThat(a.getUuid()).as("check uuid").isEqualTo(expected.getUuid()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentMetadataVersionUpdatableRelationshipsEquals(
        DocumentMetadataVersion expected,
        DocumentMetadataVersion actual
    ) {
        assertThat(actual)
            .as("Verify DocumentMetadataVersion relationships")
            .satisfies(a -> assertThat(a.getDocumentMetadata()).as("check documentMetadata").isEqualTo(expected.getDocumentMetadata()));
    }
}
