package io.lowcode.platform.domain;

import static io.lowcode.platform.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class PublicationStatusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicationStatusAllPropertiesEquals(PublicationStatus expected, PublicationStatus actual) {
        assertPublicationStatusAutoGeneratedPropertiesEquals(expected, actual);
        assertPublicationStatusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicationStatusAllUpdatablePropertiesEquals(PublicationStatus expected, PublicationStatus actual) {
        assertPublicationStatusUpdatableFieldsEquals(expected, actual);
        assertPublicationStatusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicationStatusAutoGeneratedPropertiesEquals(PublicationStatus expected, PublicationStatus actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicationStatusUpdatableFieldsEquals(PublicationStatus expected, PublicationStatus actual) {
        assertThat(actual)
            .as("Verify PublicationStatus relevant properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a ->
                assertThat(a.getPublicationStatusName()).as("check publicationStatusName").isEqualTo(expected.getPublicationStatusName())
            )
            .satisfies(a ->
                assertThat(a.getPublicationStatusCode()).as("check publicationStatusCode").isEqualTo(expected.getPublicationStatusCode())
            )
            .satisfies(a -> assertThat(a.getFlagActive()).as("check flagActive").isEqualTo(expected.getFlagActive()))
            .satisfies(a -> assertThat(a.getCreateUser()).as("check createUser").isEqualTo(expected.getCreateUser()))
            .satisfies(a ->
                assertThat(a.getCreatedAt())
                    .as("check createdAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreatedAt())
            )
            .satisfies(a -> assertThat(a.getUpdateUser()).as("check updateUser").isEqualTo(expected.getUpdateUser()))
            .satisfies(a ->
                assertThat(a.getUpdatedAt())
                    .as("check updatedAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getUpdatedAt())
            )
            .satisfies(a -> assertThat(a.getUuid()).as("check uuid").isEqualTo(expected.getUuid()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicationStatusUpdatableRelationshipsEquals(PublicationStatus expected, PublicationStatus actual) {
        assertThat(actual)
            .as("Verify PublicationStatus relationships")
            .satisfies(a -> assertThat(a.getPublication()).as("check publication").isEqualTo(expected.getPublication()));
    }
}
